### PR TITLE
New version of gpb: 4.3.1

### PR DESCRIPTION
**Pull request by tomas-abrahamsson**
New version of gpb: [4.3.1](https://github.com/tomas-abrahamsson/gpb/blob/4.3.1/ChangeLog)

### CODE REVIEW

**Comment by lrascao** [comment]
mind rebasing this onto develop? i've already merged the 4.3.0 bump

**Comment by tomas-abrahamsson** [comment]
Absolutely, I'll fix, just a sec

**Comment by tomas-abrahamsson** [comment]
Rebased!

**Comment by lrascao** [comment]
👍

**Pull request merged**
