### PR TITLE
New version of gpb: 4.10.1

### PR DESCRIPTION
**Pull request by tomas-abrahamsson**
New version of gpb: [4.10.1](https://github.com/tomas-abrahamsson/gpb/blob/4.10.1/ChangeLog)

### CODE REVIEW

**Comment by tomas-abrahamsson** [comment]
Hmm, the travis-ci build failures seem unrelated, (`wget` failed with error code 8 = "Server issued an error response." during installation of Erlang)

**Comment by lrascao** [comment]
@tomas-abrahamsson could you please rebase onto latest develop so this can go through new otp versions already?

**Comment by tomas-abrahamsson** [comment]
Done!

**Comment by lrascao** [comment]
this is merged, for some reason github thinks it's not, closing
thanks!

**Pull request closed without merging**
