### PR TITLE
JUST TESTING: New version of gpb: 3.23.0

### PR DESCRIPTION
**Pull request by tomas-abrahamsson**
New version of gpb: [3.23.0](https://github.com/tomas-abrahamsson/gpb/blob/3.23.0/ChangeLog)

### CODE REVIEW

**Comment by lrascao** [comment]
Looks good, can i go ahead and merge it or are you still working on it?

**Comment by tomas-abrahamsson** [comment]
Yes, 3.23.0 should be fully mergeable, the script will land in a later version.
If you have any comments on it, or the format of the text or anything, I'll be happy to make any change. https://github.com/tomas-abrahamsson/gpb/blob/send-pr-to-rebar3-gpb-plugin/helpers/send-pr-to-rebar3-gpb-plugin

**Comment by lrascao** [comment]
No changes necessary, looks pretty standard
thanks!

**Comment by tomas-abrahamsson** [comment]
Thanks! I'll use it as is then (the "JUST CHECKING" text removed of course)

**Pull request merged**
